### ISSUE TITLE
完成后台登录模块

### ISSUE THREAD

**Issue by TXZdream** [sysu-SAAD-project/service-end#1]
1. 从前端获取code
2. 发往验证，并根据是否存在决定是否需要添加至数据库
3. 发回token

**Comment by starthemoon** [comment]
前端模块：add
1. currentUserLogin：当前用户登录微信服务端，并将返回的code发送给本服务端，最后将本服务端返回的token进行本地存储
2.checkWhetherTokenExists：检查本地缓存是否有token，如果有发送则给服务端，否则进行当前用户登录
3.saveTokenOfCurrentUser：本地存储本服务端返回的token

所有的调用均在app的onLaunch里，目前并不清楚调用次数

**Comment by TXZdream** [comment]
## postman测试结果
完成postman测试的用户登录模块
## 未检查内容
未检查用户已在数据库中的情况

**Comment by TXZdream** [comment]
@iamxiaoyubei 在用户注册、登录时，后台向微信服务器换取的内容除openid外，还有一个叫做session_key的东西，这里有相关说明[api文档](https://developers.weixin.qq.com/miniprogram/dev/api/signature.html#wxchecksessionobject)，意味着这个字段在之后会被用到，而当前代码并没有存储这个字段，因此现在需要在数据库中加入该字段并对后段代码进行修改，从而存储该字段

**Comment by iamxiaoyubei** [comment]
@TXZdream 
请将数据库设计字段图更新以及将sql发送给我，我根据此来更新，只需要拿到session_key后存储即可是不？

**Comment by TXZdream** [comment]
更新的字段在服务端的`init/db.sql`有，目前只能说这个应该是应该的标准了，其余的还需要进行确认

**Comment by TXZdream** [comment]
你说的没错，每次拿到session_key都需要进行更新，然而数据库设计时候并没考虑，我在周日晚会进行更新，你暂时使用`session_key`字段作为数据库表头

**Comment by TXZdream** [comment]
另外就是，我不确定每次请求openid时的key是否完全一致，因此可能你需要加一道工序，或者每次拿到key都去更新一下，或者你看到文档说key一样的就可以不管

**Comment by iamxiaoyubei** [comment]
这个key存储之后是用来做什么作用的？反正目前就是我拿到key之后就重新存在数据库中哈

**Comment by TXZdream** [comment]
嗯嗯，具体的作用我上面给的链接有说，大概就是用来校验数据的，防止数据被第三方更改的，类似我们token内的加密字段吧

**Comment by iamxiaoyubei** [comment]
init中没有session_key

**Comment by iamxiaoyubei** [comment]
线下讨论一下session_key
