### ISSUE TITLE
用户获取自己报名的活动列表

### ISSUE THREAD

**Issue by TXZdream** [sysu-SAAD-project/service-end#2]
完成接口部分，需要以下内容：
1. 判断用户合法性，此时需要验证header中的token合法性
2. 判断用户是否存在于数据库
3. 根据数据库内容决定返回内容以及状态码，若为空，则状态码应为204

**Comment by TXZdream** [comment]
合法性检查可暂时空出，等待txzdream的合法性检查函数完成

**Comment by TXZdream** [comment]
合法性检查已完成，详见controller/service

**Comment by TXZdream** [comment]
使用token为`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1MjcyNjIxMDcsImlhdCI6MTUyNjA1MjUwNywic3ViIjoib1hSb2UwZWVKUG50bmJOMUx5SUR3MUdEXzRMUSJ9.VFDQNloc78CsmoZJ6dkIWQzWnDqBrK05XV4nlk8bCDo`
无法完成测试，显示为401，本token为用户数据库的第二个用户直接利用生成token的函数生成，请查明

**Comment by TXZdream** [comment]
使用postman可以获得用户的活动列表

**Comment by TXZdream** [comment]
接口修改，需要更改代码

**Comment by iamxiaoyubei** [comment]
我看后端已经成功完成了的，前端也经过了确认，ok了
